### ISSUE TITLE
Verify exp claim without verifying jwt

### ISSUE THREAD

**Issue by jamesstonehill** [jwt/ruby-jwt#281] opened 2018-09-07 11:37 UTC
There is no way to verify the exp claim without verifying the JWT. It would be nice to be able to verify a specific claim.

```ruby
exp = Time.now.to_i - 4 * 3600
exp_payload = { exp: exp }

token = JWT.encode exp_payload, 'asdf', 'HS256'

# This does not verify the expiration
decoded_token = JWT.decode token, nil, false, { verify_expiration: true }

decoded_token = JWT.decode token, nil, true, { verify_expiration: true }
# => No verification key available (JWT::DecodeError)
```

**Comment by gchapim** [comment] 2019-01-17 16:59
:+1: to this

**Comment by jamesstonehill** [comment] 2019-01-17 19:42
I opened a PR for this issue https://github.com/jwt/ruby-jwt/pull/287

**Comment by wenderjean** [comment] 2019-02-20 18:02
Since this issue was attended by pull request #295, can we closed it? @excpt

**Comment by excpt** [comment] 2019-02-20 18:06
@wenderjean Cleary yes. :)

**Closed by excpt** 2019-02-20 18:06 UTC
Labels: feature

**Comment by dkam** [comment] 2022-01-16 23:20
Is it by design that verification passes when `verify_expiration: true` is given, but there's no expiry set in the token?  

I want to ensure that an exp is set and this seemed like a good way to achieve that. I'm aware that I can check `exp` exists in the payload after decoding, but I liked the idea of JWT raising an exception if `verify_expiration: true` was given with no `exp`.

**Comment by danleyden** [comment] 2022-01-17 07:46
@dkam I believe this is intentional and correct behaviour. Because the `exp` claim is optional (see https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4) the token is not considered to have expired if there is no `exp` claim. The `verify_expiration` option is there to allow you to ignore the claim in the unusual case that you need to.

If your policy is to require an `exp` claim, you need to specify it as a required claim - see https://github.com/jwt/ruby-jwt#required-claims

**Comment by dkam** [comment] 2022-01-17 12:45
Thank @danleyden - required claim does exactly what I was after.
