### ISSUE TITLE
JWT not being signed

### ISSUE THREAD

**Issue by KramerJera** [jwt/ruby-jwt#594] opened 2024-05-02 21:17 UTC
I had the following payload:
`payload = { email: 'test@email.com', token: 'my-token'}`

and a secret just like the docs example:
`hmac_secret = 'my$ecretK3y'`

when I ran the encode command I got:
```
token = JWT.encode payload, hmac_secret, 'HS256'
 => "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidG9rZW4iOiJteS10b2tlbiJ9.PgSD1QprnxMxrJrmgyuFrhCEtX3ulEOzh6cJSg1oVLk" 
 ```

decoding the JWT using the secret, I got the payload back, just like expected:
```
decoded_token = JWT.decode token, hmac_secret, true, { algorithm: 'HS256' }
 => [{"email"=>"test@email.com", "token"=>"my-token"}, {"alg"=>"HS256"}] 
 ```

but even decoding without the secret I got the same result:
```
decoded_token = JWT.decode token, nil, false
 => [{"email"=>"test@email.com", "token"=>"my-token"}, {"alg"=>"HS256"}] 
```

What am I doing wrong? It that a bug?

**Comment by anakinj** [comment] 2024-05-14 14:41
Hi,

You are passing `false` as the last parameter to the `decode` method. That will not validate the signature but only return the payload without verifying the validity of the token.

So works as intended I would say.

**Comment by anakinj** [comment] 2024-06-17 19:00
Closing this, please reopen if there is something unclear still

**Closed by anakinj** 2024-06-17 19:00 UTC
